/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.EntregadorDAO;
import DTO.CadEntregadorDTO;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gabrielly
 */
public class FrmEntregador extends javax.swing.JFrame {

    /**
     * Creates new form FrmEntregador
     */
    public FrmEntregador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeEntregador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTelefoneEntregador = new javax.swing.JTextField();
        btnCadEntregador = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        txtEmpresaTrab = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtNomeEntregador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 340, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Entregador:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 58, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Telefone do Entregador:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtTelefoneEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneEntregadorActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefoneEntregador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 340, -1));

        btnCadEntregador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadEntregador.setText("Cadastrar Entregador");
        btnCadEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadEntregadorActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadEntregador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 160, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Empresa que faz as entregas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(txtEmpresaTrab, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 340, -1));

        jPanel2.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Cadastro de Entregador");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadEntregadorActionPerformed
        
        String nomeEntregador;
        String telefoneEntregador;
        String empresaTrablha;
        
        nomeEntregador = txtNomeEntregador.getText();
        telefoneEntregador = txtTelefoneEntregador.getText();
        empresaTrablha = txtEmpresaTrab.getText();

        CadEntregadorDTO objEntregadorDto = new CadEntregadorDTO();
        objEntregadorDto.setNomeEntregador(nomeEntregador);
        objEntregadorDto.setTelefoneEntregador(telefoneEntregador);
        objEntregadorDto.setEmpresaTrabalha(empresaTrablha);

        EntregadorDAO objEntregadorDao = new EntregadorDAO();
        try {
            objEntregadorDao.cadastrarEntregador(objEntregadorDto);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmEntregador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadEntregadorActionPerformed

    private void txtTelefoneEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneEntregadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneEntregadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEntregador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadEntregador;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtEmpresaTrab;
    private javax.swing.JTextField txtNomeEntregador;
    private javax.swing.JTextField txtTelefoneEntregador;
    // End of variables declaration//GEN-END:variables
}
